// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDShu_ZWqSM20D_iC8nhPAt0b4cUkXS97k',
    appId: '1:205057172851:web:1fbab545029b8de61d5106',
    messagingSenderId: '205057172851',
    projectId: 'blood-link-67941',
    authDomain: 'blood-link-67941.firebaseapp.com',
    storageBucket: 'blood-link-67941.firebasestorage.app',
    measurementId: 'G-5HR5JHB5FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCCUxEKoPwm2N9qAo-s6uLIKpFJezNBE',
    appId: '1:205057172851:android:842ad653f0bcc0431d5106',
    messagingSenderId: '205057172851',
    projectId: 'blood-link-67941',
    storageBucket: 'blood-link-67941.firebasestorage.app',
  );
}
